name: gafi_mall_app

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.5.0
  google_sign_in: ^6.6.0
  provider: ^6.3.0
